# Generated by Django 3.2.8 on 2021-11-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='UUid_Token',
            field=models.UUIDField(default='1b41c7cb-ec41-43ef-b62a-2f00a421fa76', editable=False),
        ),
    ]
