# Generated by Django 3.2.8 on 2021-11-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('Fullname', models.CharField(max_length=200, null=True)),
                ('organization', models.CharField(max_length=200, null=True)),
                ('Billing_Addresss', models.CharField(max_length=500, null=True)),
                ('Bill_Number', models.BigAutoField(primary_key=True, serialize=False)),
                ('User', models.IntegerField()),
                ('Date_Created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.IntegerField()),
                ('Ordered_Product', models.CharField(max_length=20)),
                ('Order_Product_Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notification_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender_id', models.IntegerField()),
                ('Receiver_id', models.IntegerField()),
                ('Topic', models.CharField(max_length=200)),
                ('Date_Created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Creation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_For', models.IntegerField()),
                ('Created_By', models.IntegerField()),
                ('Product_Id', models.IntegerField()),
                ('Product_Type', models.CharField(max_length=20)),
                ('is_Completed', models.BooleanField(default=False)),
                ('Payment_Made', models.BooleanField(default=False)),
                ('Payment_Released', models.BooleanField(default=False)),
                ('Is_Proof_Url', models.BooleanField(default=False)),
                ('Is_Delivery_Time', models.BooleanField(default=False)),
                ('Is_Pyament_Released', models.BooleanField(default=False)),
                ('Is_Payment_peding', models.BooleanField(default=True)),
                ('Is_Disputed', models.BooleanField(default=False)),
                ('Is_Realesed_Requested', models.BooleanField(default=False)),
                ('Date_Created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
