# Generated by Django 3.2.8 on 2021-11-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proof_Url', models.URLField()),
                ('Proof_Url_Scnd', models.URLField(blank=True)),
                ('Proof_Url_Third', models.URLField(blank=True)),
            ],
        ),
    ]
